# Generated by Django 3.1.12 on 2024-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSupp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(default='NA', max_length=255)),
                ('campaign_name', models.CharField(default='NA', max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('number_of_employees', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
